framework:
  messenger:
    default_bus: messenger.bus.command
    buses:
      messenger.bus.command:
        # disable the default middleware
        default_middleware: true
      messenger.bus.query:
        # disable the default middleware
        default_middleware: true
          #transports:
          # https://symfony.com/doc/current/messenger.html#transport-configuration
          # async: '%env(MESSENGER_TRANSPORT_DSN)%'
          # failed: 'doctrine://default?queue_name=failed'
          # sync: 'sync://'

          #routing:
          # Route your messages to the transports
          # 'App\Message\YourMessage': async
