framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        default_middleware: true
        middleware:
          - middleware.trace.request
          - middleware.trace.message
          - middleware.logging.command
          - middleware.execution_time
      query.bus:
        # disable the default middleware
          #transports:
          # https://symfony.com/doc/current/messenger.html#transport-configuration
          # async: '%env(MESSENGER_TRANSPORT_DSN)%'
          # failed: 'doctrine://default?queue_name=failed'
          # sync: 'sync://'

      event-broker.bus:
        default_middleware: allow_no_handlers
