macth_authors:
  path: /author/match
  controller: Colybri\Library\Entrypoint\Controller\Author\MatchAuthorController
  methods: GET

get_author:
  path: /author/{id}
  controller: Colybri\Library\Entrypoint\Controller\Author\GetAuthorController
  methods: GET

create_author:
  path: /author
  controller: Colybri\Library\Entrypoint\Controller\Author\CreateAuthorController
  methods: POST

update_author:
  path: /author
  controller: Colybri\Library\Entrypoint\Controller\Author\UpdateAuthorController
  methods: PUT

delete_author:
  path: /author/{id}
  controller: Colybri\Library\Entrypoint\Controller\Author\DeleteAuthorController
  methods: DELETE

