seek_edition:
  path: /edition/seek
  controller: Colybri\Library\Entrypoint\Controller\Edition\SeekEditionController
  methods: GET

edition:
  path: /edition/{id}
  controller: Colybri\Library\Entrypoint\Controller\Edition\GetEditionController
  methods: GET

create_edition:
  path: /edition
  controller: Colybri\Library\Entrypoint\Controller\Edition\CreateEditionController
  methods: POST

update_edition:
  path: /edition
  controller: Colybri\Library\Entrypoint\Controller\Edition\UpdateEditionController
  methods: PUT

delete_edition:
  path: /edition/{id}
  controller: Colybri\Library\Entrypoint\Controller\Edition\DeleteEditionController
  methods: DELETE

