# Set custom paths for the log files. If left empty,
# Filebeat will choose the paths depending on your OS.
#var.paths:

filebeat.modules:
- module: postgresql
  log:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths:
      - /var/log/postgresql
    #Input configuration (advanced). Any input configuration option
    #can be added under this section.
    #input:

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*/*.log
    json.add_error_key: true
    json.keys_under_root: true
    json_message_key: log



output.elasticsearch:
  enabled: true
  hosts: ["library_elastic:9200"]
  username: elastic
  password: xDJdke434SADeasd
  pipeline: library_logs
  indices:
    - index: "library-events"
      when.contains:
        channel: "library-event-published"
    - index: "library-commands"
      when.contains:
        channel: "library-simple-message"
    - index: "webserver"
      when.contains:
        msg: "handled request"

setup.template:
  enabled: true
  name: 'library'
  pattern: 'library-*'
  overwrite: false
  json:
    enabled: true
    path: "template.json"
    name: "library"
