monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
    simple-message:
      type:  rotating_file
      path: '%kernel.logs_dir%/library-simple-message/%kernel.environment%.log'
      level: info
      max_files: 10
      channels: ["library-simple-message"]
      formatter: monolog.formatter.json
