# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    service_name: 'library'
    write_db: '%env(DATABASE_URL)%'
    read_db: '%env(DATABASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
      autowire: false      # Automatically injects dependencies in your services.
      autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Colybri\Library\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Colybri\Library\Entrypoint\Controller\:
        resource: '../src/Entrypoint/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@messenger.bus.command'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@messenger.bus.query'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Colybri\Library\Application\Command\:
      autowire: true
      autoconfigure: true
      resource: '../src/Application/Command/*/*/*Handler.php'
      tags: [ { name: messenger.message_handler, bus: messenger.bus.command } ]

    Colybri\Library\Application\Query\:
      autowire: true
      autoconfigure: true
      resource: '../src/Application/Query/*/*/*Handler.php'
      tags: [ { name: messenger.message_handler, bus: messenger.bus.query } ]


    Colybri\Library\Domain\Service\:
      autowire: true
      autoconfigure: true
      resource: '../src/Domain/Service'

    Colybri\Library\Infrastructure\Persistence\Doctrine\Repository\:
      autoconfigure: true
      autowire: true
      public: true
      resource: '../src/Infrastructure/Persistence/Doctrine/Repository'
      exclude:
        - '../src/Infrastructure/Persistence/Doctrine/Repository/*/{Event,Exception}'
      bind:
        Doctrine\DBAL\Connection $connectionWrite: '@connection_write.dbal'
        Doctrine\DBAL\Connection $connectionRead: '@connection_read.dbal'

    Colybri\Library\Infrastructure\Messenger\Controller\AllHandledStampExtractor:
      class: Colybri\Library\Infrastructure\Messenger\Controller\AllHandledStampExtractor


imports:
  - { resource: context/connections.yaml }
