create_book:
  path: /book
  controller: Colybri\Library\Entrypoint\Controller\Book\CreateBookController
  methods: POST

update_book:
  path: /book
  controller: Colybri\Library\Entrypoint\Controller\Book\UpdateBookController
  methods: PUT

delete_book:
  path: /book/{id}
  controller: Colybri\Library\Entrypoint\Controller\Book\DeleteBookController
  methods: DELETE
