create_book:
  path: /book
  controller: Colybri\Library\Entrypoint\Controller\Book\CreateBookController
  methods: POST

search_books:
  path: /book/search
  controller: Colybri\Library\Entrypoint\Controller\Book\SearchBookController
  methods: GET