name: Workflow name
description:
on: [ push , pull-request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: Step 1

        run: echo "!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
          run: |
            echo "Job Context: $JOB_CONTEXT"
            echo "Done!"
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - uses: symfonycorp/security-checker-action@v2
